# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa06d38a4bbaf995bbf30cab27350c92462358ded9a679ee4be8b8ea6944d6c50adacc4c6e9262f92ac4db0158d6b33fd76663febfdae9c7e7da581dab8ed8d4

test:
  secret_key_base: bd6e310fdc26b530178d3cbae2b36dd972bf72a8aad26c857d6f066c13ecaf59a975bc6c35e2f70bc14ca37ee5f508615370cf838e7afd55e7036e2559c002c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
